# Generated by Django 3.1.6 on 2021-11-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
