# Generated by Django 3.1.6 on 2021-11-30 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_player_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
    ]
