# Generated by Django 3.1.6 on 2021-12-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20211130_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='win_rate',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
