# Generated by Django 3.1.6 on 2021-12-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_team_win_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='full_name',
            field=models.CharField(default=models.CharField(max_length=15), max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_team',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
