# Generated by Django 3.2.8 on 2021-11-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=40)),
                ('email_address', models.CharField(max_length=45)),
                ('profile_image_url', models.URLField(blank=True)),
                ('friends', models.ManyToManyField(related_name='_mini_fb_profile_friends_+', to='mini_fb.Profile')),
            ],
        ),
    ]
