# Generated by Django 3.1.6 on 2021-11-09 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0004_auto_20211104_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(1994, 1, 1, 0, 0)),
        ),
    ]
