# Generated by Django 3.1.6 on 2021-11-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0007_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
