# Generated by Django 3.1.6 on 2021-11-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0008_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='_profile_friends_+', to='mini_fb.Profile'),
        ),
    ]
